### ISSUE TITLE
Evaluating an answer without clicking 'Check Answer'

### ISSUE THREAD

**Issue by shannpersand** [jewlofthelotus/SlickQuiz#34]
Hello! Thanks for putting this plugin out there. I was just wondering if there is an easy way to change the 'Check Answer' action to fire as soon as an option is selected, or if you have any suggestions for immediately evaluating whether the answer is correct/incorrect upon selection.

**Comment by blfeigel** [comment]
@shannpersand would you be interested in sharing how you got this to work? I'm interested in doing the same.

**Comment by shannpersand** [comment]
@blfeigel sure, it's been a long time since I looked at this, I'm sure this is an incredibly inefficient way to do it:

https://gist.github.com/shannpersand/917535d68df2a26b35fc

You'll probably just have to change the level of selection. I was doing a quiz where the radio buttons would turn red/green on click based on if you got the question right or wrong.

**Comment by blfeigel** [comment]
I'm finally back on this and was able to get the correct response to show when you click an answer input, but it seems to have broken the next button.

<code>
// Bind "check answer" to any click on answer -- This function was added by NFCU
            $(_element + ' ' + _answers).find('input[type=radio]').on('click', function(e) {
				e.preventDefault(); 
				plugin.method.checkAnswer(this, {callback: plugin.config.animationCallbacks.checkAnswer});				               
			}); </code>

Any ideas?

**Comment by blfeigel** [comment]
Figured it out, in order to do this preventUnanswered needs to be false.
