### ISSUE TITLE
Adding images or video

### ISSUE THREAD

**Issue by sandeepmj** [jewlofthelotus/SlickQuiz#78]
Is it possible to add videos or images as part of the question or answers?

**Comment by jewlofthelotus** [comment]
Yes, you should be able to enter any standard HTML within the Q&A values.

**Comment by sandeepmj** [comment]
Great. Thanks. I tried adding <img scr="imageLinkHere.jpg"> within q:

"q": "<p>How many oranges?<p><p><img scr="imageLinkHere.jpg"></p>",

but it seemed to break it. will try again. Thanks so much. awesome work.

**Comment by sandeepmj** [comment]
oooh, never mind, i updated with:

`"q": "<p>How many oranges?<p>"+
            '<img src="orange.jpg">',`

And it works great!
